[project]
name = "booklet"
version = "0.1.0"
description = "generate entire audiobooks from a single 5 second voice clip, all offline!"
readme = "README.md"
requires-python = "==3.11.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "ebooklib>=0.20",
    "k2>=0.3.0",
    "nltk>=3.9.2",
    "pdfplumber>=0.11.9",
    "psutil>=7.2.2",
    "pyside6>=6.10.2",
    "python-docx>=1.2.0",
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"

[tool.uv.sources]
linacodec = { git = "https://github.com/ysharma3501/LinaCodec.git" }
