[project]
name = "booklet"
version = "0.1.0"
description = "generate entire audiobooks from a single 5 second voice clip, all offline!"
readme = "README.md"
requires-python = "==3.13.3"
dependencies = [
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu128"

[tool.uv.sources]
linacodec = { git = "https://github.com/ysharma3501/LinaCodec.git" }
